=== frankdc17/parcial1-tpi/Parcial1-Parte3/registro_facturas_grupo07.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
 <!--III.1.3 Definicion tipo simple 1-->
  <xs:simpleType name="tipogenero" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="masculino" />
      <xs:enumeration value="femenino" />
    </xs:restriction>
  </xs:simpleType>
  
    <!--III.1.3 Definicion tipo simple 2-->
  <xs:simpleType name="compania" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="claro" />
      <xs:enumeration value="tigo" />
      <xs:enumeration value="movistar" />
      <xs:enumeration value="digicel" />
    </xs:restriction>
  </xs:simpleType>
  
  <!--III.1.3 Definicion tipo simple 3-->
  <xs:simpleType name="tipoFactura" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="credito" />
      <xs:enumeration value="final" />
    </xs:restriction>
  </xs:simpleType>  
  
  <!--III.1.3 Definicion tipo cantidades-->
    <xs:simpleType name="cantidades">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="499"/>
    </xs:restriction>
  </xs:simpleType>

    <!--III.1.3 Restriccion de cantidades-->
    <xs:simpleType name = "restDui">
      <xs:restriction base="xs:string">
      <xs:length value="10"/>
    </xs:restriction>
    </xs:simpleType>
    
     <!--III.1.3 Referencia-->
    <xs:element name="divisa">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="moneda" type="xs:string"/>
                          <xs:element name="valor" type="xs:double"/>
                        </xs:sequence>  
                      </xs:complexType>  
    </xs:element>
  
  <xs:element name="registro" >
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="responsable" minOccurs="1" maxOccurs="1" />
        
        <xs:element name="factura" minOccurs="1" maxOccurs="100">
          <xs:complexType>
            <xs:sequence>
            
            <!-- ***************    III.1.2  Expresion regular 1 ********************-->
              <xs:element name="num">
                <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{3,10}"/>
                        </xs:restriction>
                      </xs:simpleType>  
              </xs:element>
              <!--Inicio bloque clientes-->
              <xs:element name="cliente">
                <xs:complexType>
                  <xs:sequence>
                  
                    <xs:element name="nombre"/>
                    
                    <xs:element name="documento">
                      <xs:complexType>
                        <xs:choice>
                        
                          <xs:element name="dui">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="restDui">
                                  <xs:attribute name="vence" type="xs:date" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          
                          <xs:element name="pasaporte">
                            <xs:complexType>
                               <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="pais" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent> 
                            </xs:complexType>
                          </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                    
                    <xs:element name="telefono">
                      <xs:complexType>
                        
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="tipo" type="xs:string" use="optional"/>
                            <xs:attribute name="cia" type="compania" use="optional"/>   
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>                    
                    </xs:element>
                    
                    <!-- ***************    III.1.2  Expresion regular 2 ********************-->
                    <xs:element name="email">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z0-9A-Z]{3,10}@(gmail|yahoo|hotmail)[\.]{1}[a-zA-Z]{3,4}"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    
                    
                    
                  </xs:sequence>
                  <xs:attribute name="codigo"/>
                  <xs:attribute name="sexo" type="tipogenero"/>  
                </xs:complexType>  
              </xs:element>
              <!--Fin del bloque de clientes-->
                
              <xs:element name="direccion" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:choice>
                    <xs:element name="casa"/>
                    <xs:element name="oficina"/>
                  </xs:choice>
                  <xs:attribute name="depto"/>
                  <xs:attribute name="municipio"/>
                </xs:complexType>  
              </xs:element>
              <!--fin del bloque de direccion-->
              
              <xs:element name="lineafactura" >
                <xs:complexType>
                  <xs:sequence>
                  
                    <xs:element name="codigo">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="tipo"/>
                          </xs:extension>  
                        </xs:simpleContent>
                      </xs:complexType>  
                    </xs:element>
                    
                    <xs:element name="detalle"/>
                    
                    <xs:element name="cantidad" type="cantidades"/>
                    
                    <xs:element name="precio">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="moneda" type="xs:string"/>
                          <xs:element name="valor" type="xs:double"/>
                        </xs:sequence>  
                      </xs:complexType>  
                    </xs:element>
                    
                    <xs:element name="subtotal">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="moneda" type="xs:string"/>
                          <xs:element name="valor" type="xs:double"/>
                        </xs:sequence>  
                      </xs:complexType>  
                    </xs:element>
                    
                  </xs:sequence>
                  <xs:attribute name="factura"/>  
                </xs:complexType>  
              </xs:element>
              <!--Fin del bloque de linea de factura-->
              
              <xs:element name="total">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="moneda"/>
                    <xs:element name="valor"/>
                  </xs:sequence>  
                </xs:complexType>  
              </xs:element>
              <!--Fin del bloque total-->

              
            </xs:sequence>
            <xs:attribute name="tipo" type="tipoFactura"/>
          </xs:complexType>        
        </xs:element>
        
      
        
      </xs:sequence>
      <xs:attribute name="periodo"/>      
    </xs:complexType>
  </xs:element>
  
  
</xs:schema>

=== frankdc17/parcial1-tpi/Parcial1-Parte3/registro_facturas_grupo07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- grupo 07  -->
<registro periodo="2012-03"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="registro_facturas_grupo07.xsd">


<responsable>Lic. Inocencio Pérez</responsable>
<!--Factura 1-->
<factura tipo="final"><num>564</num><cliente codigo="2617" sexo="femenino"><nombre>María Vélez</nombre><documento><dui vence="2018-03-03">02349867-9</dui></documento><telefono tipo="fijo">24356789</telefono><email>mariav@gmail.com</email></cliente><direccion depto="San Salvador" municipio="San Salvador"><casa>Prados del Bosque Num.23</casa></direccion><lineafactura factura="564"><codigo tipo="souvenir">498</codigo><detalle>Llavero estampas de mi pueblo: Izalco</detalle><cantidad>10</cantidad>
<precio>
<moneda>$</moneda><valor>1.13</valor>
</precio>
<subtotal>
<moneda>$</moneda>
<valor>11.30</valor>
</subtotal></lineafactura><total><moneda>$</moneda><valor>11.30</valor></total></factura>

<!--Factura 2-->
<factura tipo="credito"><num>570</num><cliente codigo="5032" sexo="femenino"><nombre>Julia Pérez</nombre><documento><pasaporte pais="USA">A98672340</pasaporte></documento><telefono tipo="celular" cia="tigo">78354926</telefono><email>jperez@yahoo.com</email></cliente><direccion depto="La Libertad" municipio="Antiguo Cuscatlan"><oficina>5 Av. Sur</oficina></direccion><lineafactura factura="570"><codigo tipo="pcportatiles">734</codigo><detalle>netbook acer a240</detalle><cantidad>3</cantidad><precio><moneda>$</moneda><valor>350.00</valor></precio><subtotal><moneda>$</moneda><valor>1050.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>1050.00</valor></total></factura>

<!--Factura 3-->
<factura tipo="credito"><num>575</num><cliente codigo="5327" sexo="masculino"><nombre>Jhon Smith</nombre><documento><pasaporte pais="USA">A98670234</pasaporte></documento><telefono tipo="celular" cia="tigo">78923546</telefono><email>jsmith@hotmail.com</email></cliente><direccion depto="La Libertad" municipio="Santa Tecla"><oficina>Final 25 Av. Norte</oficina></direccion><lineafactura factura="575"><codigo tipo="accesorio_pc">247</codigo><detalle>Mouse inalámbrico</detalle><cantidad>5</cantidad><precio><moneda>$</moneda><valor>10.00</valor></precio><subtotal><moneda>$</moneda><valor>50.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>50.00</valor></total></factura>

<!--Factura 4-->
<factura tipo="final"><num>590</num><cliente codigo="617" sexo="masculino"><nombre>Juan Pérez</nombre><documento><pasaporte pais="SLV">A40298367</pasaporte></documento><telefono tipo="celular" cia="claro">76023546</telefono><email>jperez@gmail.com</email></cliente><lineafactura factura="590"><codigo tipo="perecedero">213</codigo><detalle>Agua embotellada</detalle><cantidad>10</cantidad><precio><moneda>$</moneda><valor>0.50</valor></precio><subtotal><moneda>$</moneda><valor>5.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>5.00</valor></total></factura>

<!--Factura 5-->
<factura tipo="final"><num>593</num><cliente codigo="177" sexo="masculino"><nombre>Pedro Portillo</nombre><documento><pasaporte pais="SLV">A43698027</pasaporte></documento><telefono tipo="celular" cia="claro">76028642</telefono><email>pportillo@hotmail.com</email></cliente><lineafactura factura="593"><codigo tipo="perecedero">215</codigo><detalle>Soda enlatada</detalle><cantidad>24</cantidad><precio><moneda>$</moneda><valor>0.50</valor></precio><subtotal><moneda>$</moneda><valor>5.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>5.00</valor></total></factura>

<!--Factura 6-->
<factura tipo="credito"><num>585</num><cliente codigo="5327" sexo="masculino"><nombre>Jhon Smith</nombre><documento><dui vence="2018-06-03">02810867-0</dui></documento><telefono tipo="celular" cia="tigo">78923546</telefono><email>jsmith@yahoo.com</email></cliente><direccion depto="La Libertad" municipio="Santa Tecla"><oficina>Final 25 Av. Norte</oficina></direccion><lineafactura factura="575"><codigo tipo="accesorio_pc">247</codigo><detalle>Mouse inalámbrico</detalle><cantidad>10</cantidad><precio><moneda>$</moneda><valor>10.00</valor></precio><subtotal><moneda>$</moneda><valor>100.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>100.00</valor></total></factura>

<!--Facturas agregadas-->

<!--Factura 7-->
<factura tipo="final"><num>592</num><cliente codigo="500" sexo="femenino"><nombre>Michelle Cortez</nombre><documento><pasaporte pais="SLV">A4425654</pasaporte></documento><telefono tipo="celular" cia="tigo">75216585</telefono><email>mcortez@gmail.com</email></cliente><lineafactura factura="535"><codigo tipo="perecedero">213</codigo><detalle>Soda enbotellada</detalle><cantidad>20</cantidad><precio><moneda>$</moneda><valor>0.45</valor></precio><subtotal><moneda>$</moneda><valor>4.60</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>4.60</valor></total></factura>

<!--Factura 8-->
<factura tipo="final"><num>597</num><cliente codigo="617" sexo="masculino"><nombre>Miguel Rosario</nombre><documento><pasaporte pais="USA">A40292236</pasaporte></documento><telefono tipo="celular" cia="movistar">75632145</telefono><email>mross@hotmail.com</email></cliente><lineafactura factura="550"><codigo tipo="perecedero">300</codigo><detalle>Jugo Enlatado</detalle><cantidad>10</cantidad><precio><moneda>$</moneda><valor>0.70</valor></precio><subtotal><moneda>$</moneda><valor>7.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>7.00</valor></total></factura>

<!--Factura 9-->
<factura tipo="credito"><num>565</num><cliente codigo="5317" sexo="femenino"><nombre>Maria Ortiz</nombre><documento><pasaporte pais="USA">A92589234</pasaporte></documento><telefono tipo="celular" cia="tigo">78923546</telefono><email>usermari@hotmail.com</email></cliente><direccion depto="La Libertad" municipio="Santa Tecla"><oficina>Final 25 Av., calle las amapola</oficina></direccion><lineafactura factura="545"><codigo tipo="accesorio_pc">247</codigo><detalle>Teclado inalámbrico</detalle><cantidad>30</cantidad><precio><moneda>$</moneda><valor>10.00</valor></precio><subtotal><moneda>$</moneda><valor>300.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>300.00</valor></total></factura>

<!--Factura 10-->
<factura tipo="credito"><num>589</num><cliente codigo="5896" sexo="femenino"><nombre>Rosa Merino</nombre><documento><dui vence="2021-09-03">03840867-0</dui></documento><telefono tipo="celular" cia="claro">78923546</telefono><email>rosamer@gmail.com</email></cliente><direccion depto="La Libertad" municipio="Santa Tecla"><oficina>Final 25 Av. Sur</oficina></direccion><lineafactura factura="555"><codigo tipo="accesorio_pc">247</codigo><detalle>monitor</detalle><cantidad>1</cantidad><precio><moneda>$</moneda><valor>30.00</valor></precio><subtotal><moneda>$</moneda><valor>30.00</valor></subtotal></lineafactura><total><moneda>$</moneda><valor>30.00</valor></total></factura>

</registro>
